### PR TITLE
collect metrics in a separate go routine

### LINKED ISSUE #81: Cleanup prometheus metrics more predictably
At the moment we have a global variable for TCP metrics
https://github.com/libp2p/go-tcp-transport/blob/1b96803bf7aecc53bf0e6dfcc428916782ecbd0d/metrics.go#L23

Which has a map of connections https://github.com/libp2p/go-tcp-transport/blob/1b96803bf7aecc53bf0e6dfcc428916782ecbd0d/metrics.go#L58

That we only clear out when the metrics are collected https://github.com/libp2p/go-tcp-transport/blob/1b96803bf7aecc53bf0e6dfcc428916782ecbd0d/metrics.go#L106

We should clear out these connections more predictably (e.g. on connection close or some background goroutine).

---

There might also be a bug related to the cleanup itself https://github.com/libp2p/go-tcp-transport/blob/1b96803bf7aecc53bf0e6dfcc428916782ecbd0d/metrics.go#L110-L120

where if we're unable to get the TCP info we never clean it up. e.g. on Windows I see the following error:
```
2021-07-08T21:39:47.925-0400    ERROR   tcp-tpt go-tcp-transport@v0.2.2/metrics.go:118  Failed to get TCP info: raw-control tcp 192.168.1.6:4001: getsockopt: not implemented
```

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #81.

I really wish there was a way to pass a Prometheus struct to tcp-transport, and only collect metrics in case metrics are actually scraped. This PR introduces an eternal Go routine that periodically asks the kernel for metrics, and removes a connection from connection map when it is closed.

### CODE REVIEW

File: metrics.go [hunk 1]
```diff
@@ -103,45 +109,57 @@ func (c *aggregatingCollector) Describe(descs chan<- *prometheus.Desc) {
...
+		for _, conn := range c.conns {
+			info, err := conn.getTCPInfo()
+			if err != nil {
+				if strings.Contains(err.Error(), "use of closed network connection") {
+					c.closedConn(conn)
+					continue
+				}
+				log.Errorf("Failed to get TCP info: %s", err)
 				continue
 			}
```
Comment (aschmahmann) [inline metrics.go:131]: Is it a problem that if we `conn.getTCPInfo()` errors differently from expected then we'll never close the connection, right?

I've seen `2021-07-08T21:39:47.925-0400    ERROR   tcp-tpt go-tcp-transport@v0.2.2/metrics.go:118  Failed to get TCP info: raw-control tcp 192.168.1.6:4001: getsockopt: not implemented` on Windows so I'm concerned this could cause us problems.

File: metrics.go [hunk 2]
```diff
@@ -103,45 +109,57 @@ func (c *aggregatingCollector) Describe(descs chan<- *prometheus.Desc) {
...
-	for _, conn := range c.conns {
-		info, err := conn.getTCPInfo()
-		if err != nil {
-			if strings.Contains(err.Error(), "use of closed network connection") {
-				c.closedConn(conn)
+func (c *aggregatingCollector) cron() {
+	ticker := time.NewTicker(collectFrequency)
+	defer ticker.Stop()
+
+	for now := range ticker.C {
```
Comment (Stebalien) [inline metrics.go:116]: Making a syscall every 10 seconds for every single connection seems like a non-starter, right? Most of these connections will be idle and we can have 10-100k connections on some machines.

This just seems like it's going to be a _major_ source of background CPU usage even when we're not using metrics.

Can we instead hook into the call to `Close` (we already have a `tracingConn`)?

Comment (marten-seemann) [reply metrics.go:116]: The exact same code was executed every time Prometheus scraped metrics, which by default happens every 15s. 

We _could_ hook into `Close`, but then we'd need special treatment for cases where the peer closed the connection. More importantly, we also need the syscall for collecting RTT and packet statistics.

Comment (marten-seemann) [reply metrics.go:116]: I wish there was a way to only execute this when Prometheus is actually running. Do we have a build time / runtime flag we can use?

Comment (Stebalien) [reply metrics.go:116]: > The exact same code was executed every time Prometheus scraped metrics, which by default happens every 15s.

Only for nodes that actually care about metrics.

> We could hook into Close, but then we'd need special treatment for cases where the peer closed the connection. More importantly, we also need the syscall for collecting RTT and packet statistics.

We _always_ call close, even when the peer closes, to cleanup the connection (sockets, etc.).

> I wish there was a way to only execute this when Prometheus is actually running. Do we have a build time / runtime flag we can use?

We could wait for the first call to `Collect`, then stop when `Collect isn't called for a while. That's the best I can think of.

**Comment by mxinden** [comment]
Following up here, with the recent Slack conversations in mind.

> Only collect stats when `Collect` is called.

That is the Prometheus idiomatic way. In other words, just-in-time (on scrape / on `Collect`) metric generation, instead of pre-generated metric generation decoupled from the Prometheus scrape interval, improves data accuracy all the way to the Prometheus data store.

**Comment by BigLep** [comment]
@marten-seemann : what are the next steps here?  Who do we need a review from?

File: metrics.go (hunk 1 above)
Comment (marten-seemann) [reply metrics.go]: I tried it in my Windows VM, and I'm getting the same error. Should we disable metrics collection on Windows?

**Comment by marten-seemann** [comment]
> @marten-seemann : what are the next steps here? Who do we need a review from?

I wasn't done yet with my changes, that's why I didn't request any reviews. Now I am, and will do so.

**Comment by marten-seemann** [comment]
@aschmahmann @Stebalien I updated the PR. Now
1. we use calls to `Close` to garbage collect the connection map.
2. we start the Go routine that collects the metrics (and performs all the syscalls) when `Collect` is called, i.e. only when Prometheus is actually scraping metrics.

File: metrics.go [hunk 3]
```diff
@@ -103,45 +109,64 @@ func (c *aggregatingCollector) Describe(descs chan<- *prometheus.Desc) {
 	}
 }
 
-func (c *aggregatingCollector) Collect(metrics chan<- prometheus.Metric) {
-	now := time.Now()
+func (c *aggregatingCollector) cron() {
+	ticker := time.NewTicker(collectFrequency)
```
Comment (Stebalien) [inline metrics.go:113]: We need some way to stop this or we're going to mess with our tests.

Can we implement `Transport.Close`?

We could also auto-close this when the last connection dies, but that's slightly tricker.

**Review by Stebalien — APPROVED** [review]
One small fix but it should work otherwise.

File: metrics.go (hunk 3 above)
Comment (marten-seemann) [reply metrics.go:113]: How is this messing with our tests?
The `collector` is a global variable, and it's initialized in `init()`. On the other hand, you can have multiple transports.

Comment (Stebalien) [reply metrics.go:113]: Oh, nvm. I thought this was per-transport. In that, no, it'll be fine.
